openapi: 3.0.3
info:
  title: Base Service Api
  version: 1.0.0
servers:
  - url: 'http://localhost:8000/api'

paths:
  /service/healthcheck:
    get:
      tags:
        - "Service"
      summary: "Check service functionality"
      operationId: healthCheck
      responses:
        "200":
          description: "I'm alive"
